In [21]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [22]:
data_path = 'kc_house_data.csv'
housing = pd.read_csv(data_path)

In [23]:
price = np.array(housing['price'], np.float32)
waterfront = tf.cast(housing['waterfront'], tf.bool)
size = np.array(housing['sqft_living'], np.float32)

In [24]:
print(price)
print(waterfront)
print(size)

[221900. 538000. 180000. ... 402101. 400000. 325000.]
tf.Tensor([False False False ... False False False], shape=(21613,), dtype=bool)
[1180. 2570.  770. ... 1020. 1600. 1020.]


In [25]:
# linear regression

# define the intercept and slope
intercept = tf.Variable(0.1, np.float32)
slope = tf.Variable(0.1, np.float32)

In [26]:
# define linear regression function model
def linear_regression(intercept, slope, feature = size):
    return intercept + feature * slope

In [27]:
# define the loss function
def loss_function(intercept, slope, targets = price, feature = size):
    predictions = linear_regression(intercept, slope)
    return tf.keras.losses.mse(targets, predictions)

In [43]:
# define optimization operation
opt = tf.keras.optimizers.Adam()

In [31]:
# minimize the loss function
for i in range(1000):
    opt.minimize(lambda: loss_function(intercept, slope), \
        var_list = [intercept, slope])   

In [ ]:
# training a linear model in batches

# defined trainable variables
intercept = tf.Variable(0.1, tf.float32)
slope = tf.Variable(0.1, tf.float32)

# load data in batches
for batch in pd.read_csv('kc_house_data.csv', chunksize = 100):
	size_batch = np.array(batch['sqft_lot'], np.float32)

	# Extract the price values for the current batch
	price_batch = np.array(batch['price'], np.float32)

	# Complete the loss, fill in the variable list, and minimize
	opt.minimize(lambda: loss_function(intercept, slope, price_batch, size_batch), var_list=[intercept, slope])
        